if (NOT DEFINED TARGET)
  if (NOT DEFINED BOOST_ROOT)
    set(BOOST_ROOT $ENV{BOOST_ROOT})
    if (NOT DEFINED BOOST_ROOT)
      set(BOOST_ROOT /usr/local)
    endif (NOT DEFINED BOOST_ROOT)
  endif (NOT DEFINED BOOST_ROOT)
  set(Boost_NO_SYSTEM_PATHS ON)
  set(Boost_INCLUDE_DIR ${BOOST_ROOT}/include)
  set(Boost_LIBRARY_DIR ${BOOST_ROOT}/lib)
endif (NOT DEFINED TARGET)
find_package(Boost 1.68 REQUIRED COMPONENTS system thread chrono filesystem regex ${REQUIRED_BOOST_COMPONENTS} )

set(Boost_USE_STATIC_LIBS OFF)
add_definitions(-DBOOST_ERROR_CODE_HEADER_ONLY)
